"""current schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-13 12:01:03.971749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.migrations.admin_console import (
    backfill_missing_quotas,
    create_admin_indexes,
    drop_admin_indexes,
    upgrade_subscription_grants,
)


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    existing_tables = set(sa.inspect(op.get_bind()).get_table_names())
    if 'admin_configuration' not in existing_tables:
        op.create_table('admin_configuration',
        sa.Column('key', sa.String(length=40), nullable=False),
        sa.Column('values_json', sa.JSON(), nullable=False),
        sa.Column('revision', sa.Integer(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('key')
        )
    if 'billing_payments' not in existing_tables:
        op.create_table('billing_payments',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('plan', sa.String(length=50), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('status', sa.String(length=30), nullable=False),
        sa.Column('provider', sa.String(length=30), nullable=False),
        sa.Column('provider_session_id', sa.String(length=100), nullable=False),
        sa.Column('provider_transaction_id', sa.String(length=150), nullable=True),
        sa.Column('order_code', sa.String(length=30), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('order_code'),
        sa.UniqueConstraint('provider_session_id'),
        sa.UniqueConstraint('provider_transaction_id')
        )
        with op.batch_alter_table('billing_payments', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_billing_payments_status'), ['status'], unique=False)
            batch_op.create_index(batch_op.f('ix_billing_payments_user_id'), ['user_id'], unique=False)

    op.create_table('workbook_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('base_revision', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('preview_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workbook_actions', schema=None) as batch_op:
        batch_op.create_index('ix_workbook_actions_owner_source', ['user_id', 'source_key', 'source_hash', 'created_at'], unique=False)

    if 'billing_subscriptions' not in existing_tables:
        op.create_table('billing_subscriptions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('plan', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=30), nullable=False),
        sa.Column('provider', sa.String(length=30), nullable=False),
        sa.Column('payment_id', sa.String(length=36), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['payment_id'], ['billing_payments.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('payment_id')
        )
        with op.batch_alter_table('billing_subscriptions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_billing_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('evidences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('cell_range', sa.String(length=50), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=True),
    sa.Column('calculation_result', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=1024), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=True),
    sa.Column('source_domain', sa.String(length=255), nullable=True),
    sa.Column('source_title', sa.String(length=512), nullable=True),
    sa.Column('source_page_url', sa.String(length=2048), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_assets_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_assets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_assets_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_assets_user_id'), ['user_id'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('requires_citation', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['report_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('scopes', sa.Text(), nullable=True))

    with op.batch_alter_table('automation_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_ms', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('source_snapshot_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.add_column(sa.Column('output_files_json', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.add_column(sa.Column('failed_step', sa.String(length=100), nullable=True))

    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), server_default=sa.text("'Asia/Ho_Chi_Minh'"), nullable=False))
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), server_default=sa.text("'file'"), nullable=False))
        batch_op.add_column(sa.Column('source_config_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.add_column(sa.Column('analysis_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('analysis_mode', sa.String(length=50), server_default=sa.text("'comprehensive'"), nullable=False))
        batch_op.add_column(sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('evidence_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('claim_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('citation_number', sa.Integer(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=50), server_default=sa.text("'VERIFIED'"), nullable=False))
        batch_op.add_column(sa.Column('support_level', sa.String(length=50), server_default=sa.text("'STRONG'"), nullable=False))
        batch_op.create_foreign_key('fk_citations_evidence_id', 'evidences', ['evidence_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_citations_claim_id', 'claims', ['claim_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_citations_report_id', 'reports', ['report_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('canonical_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('organization', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('publication_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('publication_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('doi', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('provider_source_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=20), server_default=sa.text("'vi'"), nullable=False))
        batch_op.add_column(sa.Column('abstract', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('access_status', sa.String(length=50), server_default=sa.text("'open'"), nullable=False))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=50), server_default=sa.text("'UNVERIFIED'"), nullable=False))
        batch_op.add_column(sa.Column('verification_score', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('verification_details_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.add_column(sa.Column('domain_trust', sa.String(length=50), server_default=sa.text("'UNKNOWN'"), nullable=False))
        batch_op.add_column(sa.Column('file_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('dataset_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=False))

    connection = op.get_bind()
    upgrade_subscription_grants(connection)
    create_admin_indexes(connection)
    backfill_missing_quotas(connection)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    drop_admin_indexes(op.get_bind())
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('dataset_id')
        batch_op.drop_column('file_id')
        batch_op.drop_column('domain_trust')
        batch_op.drop_column('verification_details_json')
        batch_op.drop_column('verification_score')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('access_status')
        batch_op.drop_column('abstract')
        batch_op.drop_column('language')
        batch_op.drop_column('provider_source_id')
        batch_op.drop_column('provider')
        batch_op.drop_column('doi')
        batch_op.drop_column('publication_year')
        batch_op.drop_column('publication_name')
        batch_op.drop_column('organization')
        batch_op.drop_column('canonical_url')
        batch_op.drop_column('subtitle')

    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_citations_report_id', type_='foreignkey')
        batch_op.drop_constraint('fk_citations_claim_id', type_='foreignkey')
        batch_op.drop_constraint('fk_citations_evidence_id', type_='foreignkey')
        batch_op.drop_column('support_level')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('citation_number')
        batch_op.drop_column('claim_id')
        batch_op.drop_column('evidence_id')
        batch_op.drop_column('report_id')

    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.drop_column('next_run_at')
        batch_op.drop_column('analysis_mode')
        batch_op.drop_column('analysis_prompt')
        batch_op.drop_column('source_config_json')
        batch_op.drop_column('source_type')
        batch_op.drop_column('timezone')
        batch_op.drop_column('description')

    with op.batch_alter_table('automation_runs', schema=None) as batch_op:
        batch_op.drop_column('failed_step')
        batch_op.drop_column('output_files_json')
        batch_op.drop_column('source_snapshot_json')
        batch_op.drop_column('duration_ms')

    with op.batch_alter_table('auth_accounts', schema=None) as batch_op:
        batch_op.drop_column('scopes')
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')

    op.drop_table('claims')
    with op.batch_alter_table('image_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_assets_user_id'))
        batch_op.drop_index(batch_op.f('ix_image_assets_report_id'))
        batch_op.drop_index(batch_op.f('ix_image_assets_project_id'))
        batch_op.drop_index(batch_op.f('ix_image_assets_checksum_sha256'))

    op.drop_table('image_assets')
    op.drop_table('evidences')
    with op.batch_alter_table('billing_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_subscriptions_user_id'))

    op.drop_table('billing_subscriptions')
    with op.batch_alter_table('workbook_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_workbook_actions_owner_source')

    op.drop_table('workbook_actions')
    with op.batch_alter_table('billing_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_billing_payments_status'))

    op.drop_table('billing_payments')
    op.drop_table('admin_configuration')
    # ### end Alembic commands ###
